[package]
name = "serde_default"
version = "0.1.0"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
edition = "2015"

[lib]
proc-macro = true

[dependencies]
darling = {version = "0.8.3", path = "../darling"}
quote = "0.6"
syn = "0.15.26"
proc-macro2 = "0.4.26"